export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_OK = 'CHECK_LOGIN_OK';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_OK = 'LOGOUT_USER_OK';

export const SHOW_LOADING_SPINNER = 'SHOW_LOADING_SPINNER';
export const SHOW_LOADING_SPINNER_OK = 'SHOW_LOADING_SPINNER_OK';
export const HIDE_LOADING_SPINNER = 'HIDE_LOADING_SPINNER';
export const HIDE_LOADING_SPINNER_OK = 'HIDE_LOADING_SPINNER_OK';